### ISSUE TITLE
Support VRaptor4

### ISSUE THREAD

**Issue by leocwolter** [caelum/vraptor-simple-validator#2]

**Comment by nykolaslima** [comment]
@leocwolter @Turini as we discussed in VRaptor4's issue, this plugin already support VRaptor4, right?
Can we close this?

**Comment by Turini** [comment]
:ok_hand:

**Comment by nykolaslima** [comment]
Can you close @Turini?

I don't have access to do it =(

**Comment by Turini** [comment]
done, thanks!

**Comment by nykolaslima** [comment]
Thank you.
