### ISSUE TITLE
Support some way to retrieve the errors from the validator (I can pass a visitor)

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-simple-validator#9]

**Comment by nykolaslima** [comment]
I believe we can close this issue because now we can do:
`simpleValidator.getErrors();` implemented in #17

**Comment by Turini** [comment]
what do you think @guilhermesilveira?

**Comment by guilhermesilveira** [comment]
now that is an old issue. :) the only thing i dislike about the way we implemented validators since vraptor 3 is that it's type choices (always i18n by default) is a little bit messy. it is a good point to rewrite for a 5.0, yep, closing
